# Permission use
permissions: true

# Sign text (capitals doesn't matter)
sign-text: "[Kit]"

# Auto save in minutes
autosave: 5

# Clear player's inventory and effects when he gets a kit
clear-inventory: false

# Give a kit when player joins for first time
first-join-kit:
  enabled: false
  kit: "start"
