# Permission use
permissions: true

# Sign text (capitals don't matter)
sign-text: "[Kit]"

# Auto save in minutes
autosave: 5

# Clear player's inventory and effects when he gets a kit
clear-inventory: false