name: AdvancedKits
main: com.fleynaro.advancedkits.Main
version: "${pom.version}"
author: luca28pet, fleynaro, PetteriM1
api: ["1.0.0"]
description: Kit plugin for Nukkit
website: https://github.com/Nukkit-coders/AdvancedKits

commands:
 kit:
  description: Get a kit!
  usage: "/kit <kitName>"
  permission: advancedkits.command
permissions:
 advancedkits.command:
  description: "Allows the user to run /kit command"
  default: true